[tool.poetry]
name = "odin-messaging-bot"
version = "0.1.3"
description = "A NATS/STAN Bot to publish/subscribe messages."
authors = ["adolfrodeno <amvillalobos@uc.cl>"]

[tool.poetry.dependencies]
python = "^3.8"
nest-asyncio = "^1.5.1"
asyncio-nats-client = "^0.11.4"
asyncio-nats-streaming = "^0.4.0"
aiohttp = "^3.7.4"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
