[tool.poetry]
name = "mustaching"
version = "4.0.0"
description = "A Python 3.9+ library inspired by Mr. Money Mustache to summarize and plot personal finance data given in a CSV file of transactions."
authors = ["Alex Raichev <alex@raichev.net>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.9, <4.0"
pandas = ">=1, <2"
pandera = "<1"
plotly = "<6"

[tool.poetry.dev-dependencies]
jupyter = "^1.0"
pytest = "^6"
sphinx = "^4"
pre-commit = "^2"
black = "^21"
publish-sphinx-docs = "^1"

[build-system]
requires = ["poetry>=1.0.0"]
build-backend = "poetry.masonry.api"
